{% set name = 'astroimtools' %}
{% set version = '0.3' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Astronomical Image Tools

build:
    number: {{ number }}
    skip: True [py27]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=3.2
    - matplotlib >=2.2
    - numpy {{ numpy }}
    - photutils >=0.7.2
    - scipy >=1.1
    - setuptools
    - python {{ python }}
    run:
    - astropy >=3.2
    - matplotlib >=2.2
    - numpy >=1.16
    - photutils >=0.7.2
    - scipy >=1.1
    - pytest-astropy
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}

test:
    commands:
    - imarith --help
    - imstats --help
    imports:
    - astroimtools
